#
# Copyright (C) 2025 The OrangeFox Recovery Project
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

OF_MAINTAINER := AmikuraYuki
OF_USE_GREEN_LED := 0
OF_HIDE_NOTCH := 1
OF_USE_MAGISKBOOT := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1
OF_DEFAULT_KEYMASTER_VERSION := 4.1
OF_DISABLE_MIUI_OTA_BY_DEFAULT := 1
OF_SCREEN_H := 2475
OF_STATUS_H := 108
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_CLOCK_POS := 1
OF_ALLOW_DISABLE_NAVBAR := 0
OF_FL_PATH1 := /sys/class/leds/flashlight-back
OF_FL_PATH2 := /sys/class/leds/led:torch
